version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres-cooking-app
    restart: always
    hostname: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cooking-app
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/cooking-app
      - NEXTAUTH_SECRET=my-super-auth-secret
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
